// Generated by CoffeeScript 1.6.3
var ProgressView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ProgressView = (function(_super) {
  __extends(ProgressView, _super);

  function ProgressView() {
    _ref = ProgressView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  ProgressView.prototype.initialize = function(options) {
    var bucketList, milisecondsPerPart, part, result, _i, _len, _ref1;
    this.results = options.results;
    this.student = options.student;
    this.klass = options.klass;
    this.resultsByPart = [];
    bucketList = {};
    _ref1 = this.results.models;
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      result = _ref1[_i];
      bucketList[result.get("resultBucket")] = true;
      part = result.get("part");
      if (this.resultsByPart[part] == null) {
        this.resultsByPart[part] = [];
      }
      this.resultsByPart[part].push(result);
      this.resultsByPart[part].sort(function(a, b) {
        return a.attributes.reportType < b.attributes.reportType;
      });
    }
    bucketList = _.keys(bucketList);
    milisecondsPerPart = 604800000;
    return this.currentPart = Math.round(((new Date()).getTime() - this.klass.get("startDate")) / milisecondsPerPart);
  };

  ProgressView.prototype.render = function() {
    var attempted, bucketName, bucketResult, correct, html, item, itemsPerMinute, part, timeAllowed, timeRemain, _i, _j, _k, _len, _len1, _ref1, _ref2, _ref3;
    html = "      <h1>Progress table</h1>      <h2>" + (this.student.get("name")) + "</h2>      <table class='mastery_check'>    ";
    for (part = _i = 1, _ref1 = this.currentPart; 1 <= _ref1 ? _i <= _ref1 : _i >= _ref1; part = 1 <= _ref1 ? ++_i : --_i) {
      if (this.resultsByPart[part] === void 0) {
        continue;
      }
      html += "<tr>";
      html += "<td>Week</td><td>" + part + "</td>";
      _ref2 = this.resultsByPart[part];
      for (_j = 0, _len = _ref2.length; _j < _len; _j++) {
        bucketResult = _ref2[_j];
        bucketName = bucketResult.attributes.resultBucket.titleize();
        correct = 0;
        _ref3 = bucketResult.attributes.subtestData.items;
        for (_k = 0, _len1 = _ref3.length; _k < _len1; _k++) {
          item = _ref3[_k];
          if (item.itemResult === "correct") {
            correct++;
          }
        }
        attempted = bucketResult.attributes.subtestData.attempted;
        timeRemain = bucketResult.attributes.subtestData.time_remain;
        timeAllowed = 60;
        itemsPerMinute = Math.round((correct / (timeAllowed - timeRemain)) * timeAllowed);
        html += "<td>" + bucketName + " correct</td><td>" + correct + "/" + attempted + "</td>";
        html += "<td>" + bucketName + " per minute</td><td>" + itemsPerMinute + "</td>";
      }
    }
    html += "</table>";
    this.$el.html(html);
    return this.trigger("rendered");
  };

  return ProgressView;

})(Backbone.View);
