// Generated by CoffeeScript 1.6.3
var Collections, collections, results;

Collections = Backbone.Collection.extend();

collections = new Collections();

results = new Results();

results.fetch({
  success: function(data) {
    var ob;
    ob = {};
    data.each(function(model, index) {
      return ob[index] = model.get("subtestData");
    });
    return _.each(ob, function(items, index) {
      var correct, incorrect, name;
      name = '';
      correct = 0;
      incorrect = 0;
      _.each(items, function(item) {
        var g;
        if (item.prototype === "location") {
          name = item.data['location'].join();
        }
        if (item.prototype === "survey") {
          g = item.data;
          if (g[Object.keys(g)[0]] === '1') {
            return correct++;
          } else {
            return incorrect++;
          }
        }
      });
      return collections.add({
        'state': name,
        'correct': correct,
        'incorrect': incorrect
      });
    });
  }
});
