// Generated by CoffeeScript 1.6.3
var Questions, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Questions = (function(_super) {
  __extends(Questions, _super);

  function Questions() {
    _ref = Questions.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Questions.prototype.model = Question;

  Questions.prototype.url = "question";

  Questions.prototype.db = {
    view: "questionsByAssessmentId"
  };

  Questions.prototype.comparator = function(subtest) {
    return subtest.get("order");
  };

  Questions.prototype.maintainOrder = function() {
    var i, model, ordered, subtest, test, _i, _len, _ref1, _results;
    test = ((function() {
      var _i, _len, _ref1, _results;
      _ref1 = this.models;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        model = _ref1[_i];
        _results.push(model.get("order"));
      }
      return _results;
    }).call(this)).join("");
    ordered = ((function() {
      var _i, _len, _ref1, _results;
      _ref1 = this.models;
      _results = [];
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        model = _ref1[i];
        _results.push(i);
      }
      return _results;
    }).call(this)).join("");
    if (test !== ordered) {
      _ref1 = this.models;
      _results = [];
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        subtest = _ref1[i];
        subtest.set("order", i);
        _results.push(subtest.save());
      }
      return _results;
    }
  };

  return Questions;

})(Backbone.Collection);
