// Generated by CoffeeScript 1.6.3
var IdEditView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

IdEditView = (function(_super) {
  __extends(IdEditView, _super);

  function IdEditView() {
    _ref = IdEditView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  IdEditView.prototype.initialize = function(options) {
    this.model = options.model;
    return this.parent = options.parent;
  };

  return IdEditView;

})(Backbone.View);
