// Generated by CoffeeScript 1.6.3
var KlassResults, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

KlassResults = (function(_super) {
  __extends(KlassResults, _super);

  function KlassResults() {
    _ref = KlassResults.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  KlassResults.prototype.url = "result";

  KlassResults.prototype.model = Result;

  return KlassResults;

})(Backbone.Collection);
