// Generated by CoffeeScript 1.6.3
var allResult, exchk, gotDir, gotFS, gotFile, gotFileWriter, onConfirm, onDeviceReady, onOnline;

onDeviceReady = function() {
  return document.addEventListener("online", onOnline, false);
};

onOnline = function() {
  return $.couch.replicate(Tangerine.config.address.local.dbName, Tangerine.config.address.cloud.host + "/" + Tangerine.config.address.cloud.dbName, {
    success: function() {
      return true;
    },
    error: function(a, b) {
      return false;
    }
  });
};

allResult = '';

gotFS = function(fileSystem) {
  return fileSystem.root.getDirectory("data", {
    create: true
  }, gotDir);
};

gotDir = function(dirEntry) {
  var d, strDate;
  d = new Date();
  strDate = d.getFullYear() + "-" + d.getMonth() + 1 + "-" + d.getDate() + "-" + Math.floor((Math.random() * 1000) + 1);
  return dirEntry.getFile("result" + strDate + ".json", {
    create: true,
    exclusive: false
  }, gotFile);
};

gotFile = function(fileEntry) {
  return fileEntry.createWriter(gotFileWriter);
};

gotFileWriter = function(writer) {
  writer.onwriteend = function(evt) {};
  return writer.write(JSON.stringify(allResult));
};

exchk = function() {
  return navigator.notification.confirm('Exit application ?', onConfirm, 'Warning!', 'Exit,Back');
};

onConfirm = function(button) {
  if (button === 1) {
    return navigator.app.exitApp();
  }
};
